name: SmallRye Build

on:
  push:
    branches:
      - 'main'
      - '[1-9].[0-9].x'
      - '1.x'
      - '!dependabot/**'
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    branches:
      - 'main'
      - '[1-9].[0-9].x'
      - '1.x'
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-java@v1.4.3
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: build with maven
        run: mvn -B formatter:validate impsort:check javadoc:javadoc verify -Pcoverage

      - uses: actions/upload-artifact@v2
        name: tck-report
        with:
          name: tck-report
          path: testsuite/tck/target/surefire-reports

      ## Store information about the build context for Sonar scan in separate job
      - name: Save Build Context
        run: echo "$GITHUB_CONTEXT" > target/build-context.json
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      ## Attach target directories for safe Sonar scan in separate job
      - name: Attach Build Output
        if: matrix.java == '11'
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: |
            **/target/
            !**/target/node/**/*
            !**/target/**/*.jar
            !**/target/**/*.war
